Mysql:
  User: root
  PassWord: diguo
  Host: localhost
  Port: 3306
  DataBase: mc_nancheng
  Table: drawing

Attribute:
  damage: '伤害'
  defand: '防御'
#  hit: '命中'
  dodge: '闪避'
  critical: '暴击'
  realattack: '真实伤害'
  posion: '剧毒攻击'
  flame: '火焰攻击'
  seckill: '秒杀'
  exp: '经验增加'
  value: '战斗力'
  durability: '耐久'
  unbreak: '无限耐久'

Setting:
  #当战力值超过500的时候进服会全服通告
  ValueNotice: 500
  #每次使用物品掉落多少自定义耐久
  DurDrop: 1
  #设置还剩多少耐久的时候发出警告
  DurWarn: 10



